# Generated by Django 3.2.5 on 2022-05-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('datetime', models.DateTimeField(verbose_name='trip datetime')),
                ('transport', models.CharField(max_length=64)),
                ('location_name', models.CharField(max_length=128)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('status', models.CharField(default='in review', max_length=16)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja_app.agency')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja_app.traveler')),
            ],
        ),
    ]
