# Generated by Django 3.2.5 on 2022-05-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja_app', '0003_auto_20220522_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja_app.grouptour')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja_app.traveler')),
            ],
        ),
    ]
