# Generated by Django 3.2.5 on 2022-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja_app', '0004_tourregistrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistrations',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
