# Generated by Django 3.2.5 on 2022-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja_app', '0006_alter_tourregistrations_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/agency_logos/'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/'),
        ),
    ]
